<!-- ============= 採用情報 ============= -->
<?php get_header(); ?>
<div id="container" class="container_com_ w_inner">
    <main>
        <p id="recruit_head">採用情報</p>
        <table class="table">
            <tbody>
                <tr>
                    <th>職務内容</th>
                    <td>
                        <p>
                            （１）一般事務
                            <br>・書類作成、データ入力及び管理表作成
                            <br>・その他庶務的事務
                        </p>
                        <p>
                            （２）庶務（未経験者歓迎）
                            <br>・荷物の積み下ろし搬送、会議室設営
                        </p>
                        <p>
                            （３）プログラマー、システムエンジニア
                            <br>・基幹システム開発、運用・保守
                            <br>・社内の問い合わせ対応
                        </p>
                    </td>
                </tr>
                <tr>
                    <th>雇用形態</th>
                    <td>
                        <p>正社員</p>
                    </td>
                </tr>
                <tr>
                    <th>給与</th>
                    <td>
                        <p>月給: 万～ 万円</p>
                    </td>
                </tr>
                <tr>
                    <th>諸手当</th>
                    <td>通勤手当、時間外手当</td>
                </tr>
                <tr>
                    <th>昇給・賞与</th>
                    <td>賞与/年2回</td>
                </tr>
                <tr>
                    <th>勤務地</th>
                    <td>東京都・神奈川県・福岡県</td>
                </tr>
                <tr>
                    <th>勤務時間</th>
                    <td>
                        <p>08：50～17：20（休憩時間45分）</p>
                    </td>
                </tr>
                <tr>
                    <th>時間外労働</th>
                    <td>
                        <p>月5時間程度</p>
                    </td>
                </tr>
                <tr>
                    <th>休日・休暇</th>
                    <td>
                        <p>完全週休2日制、祝日、年末年始</p>
                        <p>有給休暇</p>
                    </td>
                </tr>
                <tr>
                    <th>福利厚生</th>
                    <td>
                        <p>健康保険・厚生年金・雇用・労災等</p>
                    </td>
                </tr>
                <tr>
                    <th>応募資格</th>
                    <td>
                        <p>学歴：高卒以上</p>
                    </td>
                </tr>
                <tr>
                    <th>応募方法</th>
                    <td>
                        <p>弊社お問い合わせフォームよりお問い合わせください。</p>
                        <p>弊社採用担当者より、ご連絡いたします。</p>
                    </td>
                </tr>
            </tbody>
        </table>
    </main>
    <?php get_sidebar(); ?>
</div>
<?php get_footer(); ?>